### ISSUE TITLE
Creating a new NDK instance on each function call 

### ISSUE THREAD

**Issue by richard16611** [nostr-dev-kit/ndk#157]
I'm currently working on an application where I've implemented a function that creates a new NDK (Network Development Kit) instance on each call. This approach is contrary to the recommended practice of using a single NDK instance throughout the app. However, I find that it better suits my specific requirements for this project.
```
async function fetchEvents<K extends number>(
  filter: NDKFilter<K>,
  relays: string[],
) {
  const ndk = new NDK({ explicitRelayUrls: relays });
  await ndk.connect();

  const event = await ndk.fetchEvent(filter);
  return event;
}
```

Specific Implementation Details:

Avoiding Global State: This implementation allows me to avoid using a global state for storing the NDK, which I find beneficial.
Changing Relays: I need to change relays with each call, and this approach facilitates that.
Non-usage of Cache: I do not utilize the caching feature of the NDK, which is a common reason for maintaining a single instance.

Questions and Concerns:
Are there other advantages of using a single NDK instance that I might be missing?
Potential Problems or Performance Impacts: Could there be any unforeseen issues or performance impacts due to this implementation? I would appreciate insights into any potential drawbacks or optimization tips for this approach.

**Comment by erskingardner** [comment]
Sorry @richard16611 this question slipped through the cracks. 

The biggest drawback here is that you're creating redundant connections to relays and forcing your client to do the connection work for each new NDK instance you generate instead of sharing that connection for many different subscriptions and calls. 

If you want to tell me more about why your app needs to change relays on each call I'm happy to offer thoughts.
