### ISSUE TITLE
Does NDK have support for Nostr Login? 

### ISSUE THREAD

**Issue by aaronkopplin** [nostr-dev-kit/ndk#234]
Hi there,

Before doing anything with nostr, the user needs to log in. Does NDK provide support for this? If so, please make it more obvious in the readme and or provide an example of a simple implementation. 

If not, please make that explicit in the readme as well. would save time for new Nostr devs that dont know what theyre doing (like me!) 

Thanks!

**Comment by pablof7z** [comment]
hi

there is no such thing as "logging in" in nostr, since there are no nostr accounts. You just sign events with a key, that's the closest you can get to "logging in".

What you are looking for are "signers", of which there are multiple, NDKPrivateKeySigner, NDKNip07Signer, NDKNip46Signer, have a look at those and let me know here if you have more questions ;)
