### ISSUE TITLE
tagId should handle kind 0, 3 and 10k

### ISSUE THREAD

**Issue by brugeman** [nostr-dev-kit/ndk#34]
Right now these kinds are not de-duplicated by tagId properly.

**Comment by erskingardner** [comment]
@brugeman can you go into a bit more detail about what you'd like to see tagId do? Do kinds 0, 3, and 10 have a similarly constructed `id` as you can do with parameterized replaceable events in the 30k range?

**Comment by erskingardner** [comment]
@nostrband finally got around to chatting wit @pablof7z on this and since it's not in the NIPs we're going to call this "won't fix" for now.

**Comment by nostrband** [comment]
Dedup by kind:pubkey[:d_tag] is in NIP-01, NIP-02 and NIP-16, ndk implements them only partially - for parameterized replaceable events (30k), not for replaceable events (10k) or 0/3 kinds. That's why I'm getting stale kind:0 events from some relays bcs they're not dedupEvent-ed bcs they have different tagId. 

Or am I missing something?

**Comment by pablof7z** [comment]
aaah ok, I see what you mean now; I thought this issue was about tagging events because of the mention of the `tagId()`; I thought you were saying that tagging a replaceable event needed to be in that format, not that this was for deduplication. Fixing it.

**Comment by pablof7z** [comment]
✅
