### ISSUE TITLE
Subscription eoseTimeout causes premature EOSE

### ISSUE THREAD

**Issue by brugeman** [nostr-dev-kit/ndk#35]
Suppose I have nostr.mutinywallet.com in my relay list. This relay sends EOSE immediately on any sub. So eoseTimeout fires very early and cuts data coming from other relays. eoseTimeout should probably fire only if there was X ms from last event on this sub, not from last eose - this should handle the dead relays, but still not cut the data.

**Comment by pablof7z** [comment]
this was fixed on the NDK 1.0 release

now it expects a minimum number of relays to EOSE (iirc 50%) before timeouts are considered and then the timeout is reduced by the number of relays that are missing an EOSE.

All timeouts are ignored while events for the subscription are being received.

And subscriptions set to close on EOSE are closed at the relay level when the relay has sent the EOSE, instead of the previous functionality of waiting for the relay set to EOSE before closing subscriptions at the relay level.
